title: Sam Bordiss - Content & User Experience Designer
description: Canberra-based content & user experience designer Sam Bordiss
keywords: content,user,experience,design,accessibility,usability
author: Sam Bordiss
# twitter: 

timezone: Australia/Sydney
google_analytics: UA-160708458-1

baseurl: /

sass:
  sass_dir: /assets/sass
  style: :compressed

repository:

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default'

plugins:
  - jekyll-sitemap
